### ISSUE TITLE
Uncaught Error: Uncaught Promise Rejection

### ISSUE THREAD

**Issue by ecker00** [steelbrain/Atom-Hack#47] opened 2015-03-11 13:23 UTC
The error comes when I open a project with a .atom-hack config file. I don't know what is wrong with the connection, got RSA private key setup and working. Might be something wrong with my config file, but the read me instructions was pretty vague about it. Tried lots of different combinations in the config file.

Off-topic, side note: Would be great is this package worked with the "open-last-project" package. As the command atom.project.getPath() returns "undefined" at launch. Seems like "atom-hack" runs before the "open-last-project" package have finished loading.

**Atom Version**: 0.187.0
**System**: Mac OS X 10.10.2
**Thrown From**: [Atom-Hack](https://github.com/steelbrain/atom-hack) package, v3.3.7

### Stack Trace

Uncaught Error: Uncaught Promise Rejection

```
At /Users/ecker/.atom/packages/Atom-Hack/node_modules/node-ssh/node_modules/a-promise/lib/build/main.js:100

Error: Uncaught Promise Rejection
    at Promise._prototypeProperties.reject.value (/Users/ecker/.atom/packages/Atom-Hack/node_modules/node-ssh/node_modules/a-promise/lib/build/main.js:100:17)
    at t.<anonymous> (/Users/ecker/.atom/packages/Atom-Hack/node_modules/node-ssh/lib/build/index.js:1:964)
    at Promise.<anonymous> (/Users/ecker/.atom/packages/Atom-Hack/node_modules/node-ssh/node_modules/a-promise/lib/build/main.js:16:18)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
Atom-Hack, v3.3.7
color-picker, v1.4.4
open-last-project, v0.3.4
remote-sync, v2.4.0

# Dev
No dev packages
```

**Comment by steelbrain** [comment] 2015-03-11 15:04
I am unable to reproduce this behaviour on latest Atom v0.186 with open-last-project v0.3.1.
I am using this configuration
```js
{
  "type":"remote",
  "host":"localhost",
  "username":"steel",
  "port":22,
  "privateKey":"/home/steel/.ssh/id_rsa",
  "remoteDir":"/tmp/Temp2",
  "autoPush": true
}
```

**Comment by ecker00** [comment] 2015-03-12 09:28
My config file looks quite like yours, except that it's an external host, not localhost. I can change most other things in the config file and get a different error, but changing the host to something invalid does not make a difference, same error. Tried both via IP and domain name as host, the connection works flawlessly in other applications.

**Comment by steelbrain** [comment] 2015-03-12 09:48
From the stack trace of your bug I don't think it's a connection issue.
What's the output of running `hh_client` in the project root on the remote server?

**Comment by ecker00** [comment] 2015-03-12 09:57
At the moment, if I 'cd' to the remoteDir on the server and run hh_client it get the result: "No errors!"

I've tried to put some alerts in your code to see what data is coming though and going where. The last point I've found in your coffee script is line 25 in h.coffee , where:

@SSH = new SSH(config)
@SSH.connect().then ->
  resolve()

I think it never runs the resolve() after .connect(). The data passed into config seems fine.

**Comment by steelbrain** [comment] 2015-03-12 09:58
I recently updated Atom-Hack, have you upgraded to the latest version by the way?

**Comment by ecker00** [comment] 2015-03-12 10:10
I just uninstalled the package now and redownloaded from this repo, same result. Also tried to reinstall via the apm terminal. Same error. Says the node-ssh package is version 0.1.2, that's something apm installed on it's own.

**Comment by ecker00** [comment] 2015-03-12 13:40
Can report back that we narrowed down the issue to the latest version of ssh2. steelbrain fixed it by rolling back to an older version of ssh2

https://github.com/mscdex/ssh2/issues/246

**Comment by steelbrain** [comment] 2015-03-12 15:28
Closing because It's not really related to this repo.

**Closed by steelbrain** 2015-03-12 15:28 UTC
Labels: bug, no-repro
