### ISSUE TITLE
Skip Non-Hack PHP Files

### ISSUE THREAD

**Issue by dwlnetnl** [steelbrain/Atom-Hack#56] opened 2015-04-07 16:54 UTC
Atom-Hack interferes with 'plain' PHP (<?php not <?hh), because it generates an uncaught error on a file save. A bit annoying for my taste...

-----

**Atom Version**: 0.189.0
**System**: Mac OS X 10.10.2
**Thrown From**: [Atom-Hack](https://github.com/steelbrain/atom-hack) package, v3.5.3

### Stack Trace

Uncaught Error: could not find a .hhconfig file in / or any of its parent directories. Do you have a .hhconfig in your code's root directory?

```
At /Users/user/.atom/packages/Atom-Hack/lib/typechecker.coffee:53

Error: could not find a .hhconfig file in / or any of its parent directories. Do you have a .hhconfig in your code's root directory?

  at /Users/user/.atom/packages/Atom-Hack/lib/typechecker.coffee:53:23

```

### Commands

```
     -0:54.0 pane:show-next-item (atom-text-editor.editor.is-focused)
     -0:53.3 core:move-to-top (atom-text-editor.editor.is-focused)
     -0:52.0 core:close (atom-text-editor.editor.is-focused)
     -0:51.5 core:move-to-top (atom-text-editor.editor.is-focused)
  2x -0:51.2 core:close (atom-text-editor.editor.is-focused)
  2x -0:42.2 editor:newline (atom-text-editor.editor.is-focused)
  4x -0:40.9 core:backspace (atom-text-editor.editor.is-focused)
     -0:26.2 autocomplete-plus:confirm (atom-text-editor.editor.is-focused)
  6x -0:18.4 core:backspace (atom-text-editor.editor.is-focused)
     -0:08.2 editor:move-to-beginning-of-word (atom-text-editor.editor.is-focused)
     -0:07.6 core:move-left (atom-text-editor.editor.is-focused)
  2x -0:04.6 core:backspace (atom-text-editor.editor.is-focused)
     -0:04.1 core:move-right (atom-text-editor.editor.is-focused)
     -0:03.7 editor:move-to-end-of-screen-line (atom-text-editor.editor.is-focused)
     -0:03.0 editor:newline (atom-text-editor.editor.is-focused)
     -0:02.3 core:save (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "autocomplete"
    ]
  },
  "Atom-Hack": {
    "typeCheckerCommand": "/usr/local/bin/hh_client"
  }
}
```

### Installed Packages

```coffee
# User
Atom-Hack, v3.5.3
autocomplete-html, v0.5.0
autocomplete-phpunit, v1.0.0
autocomplete-plus, v2.8.0
language-hack, v0.1.1
linter, v0.12.0

# Dev
No dev packages
```

**Comment by steelbrain** [comment] 2015-04-07 16:57
O YEE PEOPLE!  WHY U NO SEARCH FOR EXISTING ISSUES BEFORE CREATING A NEW ONE ?! :laughing: 

Duplicate of #55 and #53

**Comment by dwlnetnl** [comment] 2015-04-07 18:33
Oops!

**Comment by steelbrain** [comment] 2015-04-07 18:34
Thanks for the bug report, I didn't read the first line at first. Sorry for being kind-of rude. :stuck_out_tongue:

**Comment by dwlnetnl** [comment] 2015-04-07 18:35
No problem!

**Comment by steelbrain** [comment] 2015-04-07 18:38
Note to @dwlnetnl: You rock :tada:

**Comment by dwlnetnl** [comment] 2015-04-07 18:40
Why?

**Comment by steelbrain** [comment] 2015-04-07 18:43
Because I had this idea for quite some time, and I didn't think it was important. Now that you have opened it up as a bug, It can be fixed.

**Closed** 2015-06-09 06:15 UTC
Labels: enhancement
