### ISSUE TITLE
Uncaught Error: could not find a .hhconfig file in /Volumes/Work/Git/php-extension-development-guides/book/chapt01 or any of its parent directories. Do you have a .hhconfig in your code's root directory?

### ISSUE THREAD

**Issue by andot** [steelbrain/Atom-Hack#55] opened 2015-04-04 04:21 UTC
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.187.0
**System**: Mac OS X 10.10.2
**Thrown From**: [Atom-Hack](https://github.com/steelbrain/atom-hack) package, v3.5.0

### Stack Trace

Uncaught Error: could not find a .hhconfig file in /Volumes/Work/Git/php-extension-development-guides/book/chapt01 or any of its parent directories. Do you have a .hhconfig in your code's root directory?

```
At /Users/andot/.atom/packages/Atom-Hack/lib/typechecker.coffee:53

Error: could not find a .hhconfig file in /Volumes/Work/Git/php-extension-development-guides/book/chapt01 or any of its parent directories. Do you have a .hhconfig in your code's root directory?

  at /Users/andot/.atom/packages/Atom-Hack/lib/typechecker.coffee:53:23

```

### Commands

```
     -0:25.9 editor:move-to-end-of-screen-line (atom-text-editor.editor.mini)
  2x -0:25.6 core:backspace (atom-text-editor.editor.mini)
     -0:23.7 core:confirm (atom-text-editor.editor.mini)
  2x -0:12.2 core:backspace (atom-text-editor.editor.is-focused)
     -0:10.2 editor:move-to-end-of-screen-line (atom-text-editor.editor.is-focused)
  6x -0:08.2 core:move-down (atom-text-editor.editor.is-focused)
     -0:06.6 editor:move-to-first-character-of-line (atom-text-editor.editor.is-focused)
  3x -0:06.4 core:delete (atom-text-editor.editor.is-focused)
     -0:04.4 editor:move-to-end-of-screen-line (atom-text-editor.editor.is-focused)
  4x -0:02.1 core:move-up (atom-text-editor.editor.is-focused)
     -0:00.9 core:save (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "seti-ui",
      "seti-syntax"
    ]
  },
  "Atom-Hack": {
    "typeCheckerCommand": "/usr/local/bin/hh_client"
  }
}
```

### Installed Packages

```coffee
# User
Atom-Hack, v3.5.0
asciidoc-preview, v0.4.3
autocomplete-paths, v1.0.2
autocomplete-plus, v2.7.1
autocomplete-snippets, v1.2.0
coffee-refactor, v0.6.2
color-picker, v1.5.0
dart-tools, v0.8.9
dash, v1.1.0
go-plus, v3.3.5
js-refactor, v0.3.0
language-asciidoc, v0.11.1
language-asp, v0.1.0
language-csharp, v0.5.0
language-d, v3.1.2
language-dart, v0.1.1
language-erlang, v2.0.0
language-hack, v0.1.1
language-ilasm, v0.0.1
language-lua, v0.9.2
language-opencl, v0.1.0
language-pascal, v0.5.0
language-r, v0.1.1
language-svg, v0.8.0
language-x86, v0.1.0
linter, v0.12.0
linter-clang, v2.25.1
linter-cpplint, v0.1.4
linter-csslint, v0.0.11
linter-golint, v0.2.0
linter-htmlhint, v0.0.12
linter-jshint, v0.1.0
linter-lua, v0.1.5
linter-perl, v0.4.2
linter-php, v0.0.12
linter-pylint, v0.2.1
localization, v1.16.1
minimap, v4.7.5
refactor, v0.4.1
seti-syntax, v0.3.3
seti-ui, v0.6.3

# Dev
No dev packages
```

**Comment by steelbrain** [comment] 2015-04-04 04:22
Dupe of #53

**Comment by steelbrain** [comment] 2015-04-04 04:22
I think I need to find a nicer way to show that error.

**Closed by steelbrain** 2015-04-04 04:22 UTC

**Comment by andot** [comment] 2015-04-04 04:29
#54
