### ISSUE TITLE
Fallback to global namespace for functions not supported in autocomplete

### ISSUE THREAD

**Issue by dwlnetnl** [steelbrain/Atom-Hack#51] opened 2015-03-18 23:52 UTC
When coding inside a namespace, there is a fallback to the global namespace for functions. This is currently not implemented in the autocompletion. (I'm using autocomplete+ by the way.)

**Comment by steelbrain** [comment] 2015-03-19 09:28
Can you please provide a minimal code snippet to reproduce the bug?

**Comment by dwlnetnl** [comment] 2015-03-19 16:43
```
<?hh
namespace N;

class C {
  public function f() {
    // here only \str<tab> works
    // not str<tab>
  }
}
```

**Comment by dwlnetnl** [comment] 2015-03-20 13:06
I've stumbled also on hh_clients autocomplete abilities. Maybe it can be integrated. This would be awesome because hh_client has full knowledge of all the valid symbols.

**Comment by steelbrain** [comment] 2015-03-20 13:10
I am successfully able to reproduce this behaviour on my machine. and Because Atom-Hack uses `hh_client` from `github.com/facebook/hhvm` for nearly everything and has __zero__ knowledge of namespaces, It can only be implemented by the hhvm folks.

**Comment by steelbrain** [comment] 2015-03-20 13:12
But maybe you're right, if we recieve an empty list of autocompletions for a scope, Atom-Hack should append `\` in front of it itself and try to get a list.

**Comment by steelbrain** [comment] 2015-04-02 17:05
Opened in HHVM repo, closing here

**Closed by steelbrain** 2015-04-02 17:05 UTC
Labels: enhancement
